resources:
  - github.com/marknazareno/gitops-apps-base/spring-boot-demo
commonLabels:
  env: prod
replicas:
  - name: spring-boot-demo
    count: 2
images:
  - name: ghcr.io/marknazareno/spring-boot-demo
    newTag: ca7cf95a75d9995e8401f750d1d55ea2a44e5834
